FROM alpine:3.11.5 as installer

ARG TERRAFORM_VERSION=0.12.24

RUN apk add --no-cache \
        curl \
        git \
        gnupg \
        openssh \
        unzip

COPY public-keys .

RUN curl -fsSL https://raw.githubusercontent.com/zahiyo/devcontainers/master/tools/terraform/install.sh -o - \
    | sh -s ${TERRAFORM_VERSION} terraform.public_key

FROM zahiyo/devcontainer-base:alpine

LABEL zahiyo.devcontainer.terraform.version="0.1"

RUN sudo apk add --no-cache openssh

COPY --from=installer ["/bin/terraform", "/bin/terraform"]

RUN terraform -install-autocomplete